### ISSUE TITLE
Options menu gone

### ISSUE THREAD

**Issue by brmonaghan** [jerrod-lankford/google-voice-desktop-app#47]
@Jerrkawz we have another problem to worry about
It seems that the options tab is gone from GV Desktop.
![voice options gone](https://user-images.githubusercontent.com/71337477/113488498-85706500-948c-11eb-948f-3163c7cf45b9.png)

**Comment by jeffjensen** [comment]
I confirm the same issue.

**Comment by Jerrkawz** [comment]
Ive noticed it but it seems intermittent. Sometimes it shows up and sometimes it doesnt. Its an injected menu and the timing with the css selectors can be finicky, ill try to look into it

**Comment by neurolizer** [comment]
I can consistently make the custom Customize icon disappear by opening the GV Settings (gear) icon in the top right and then closing it. After that, the Customize icon doesn't seem to come back until I quit and restart Voice Desktop.

**Comment by bitingsock** [comment]
If you click on the "voice" link in the top left it will reload the page, bringing the menu back

**Comment by brmonaghan** [comment]
closing as this is fixed

**Comment by jerrod-lankford** [comment]
This isnt completely fixed. Please don't close issues, ill lose track

**Comment by brmonaghan** [comment]
Oh sorry! Thanks for letting me know.
Had forgot this isnt working.

**Comment by eFail** [comment]
@jerrod-lankford I believe this can be closed now.  Was fixed by #87

**Comment by brmonaghan** [comment]
ok closing
